CREATE DATABASE task_force CHARACTER SET 'utf8';

-- **

CREATE TABLE category (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(32) NOT NULL,
	css_class VARCHAR(16) NOT NULL
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- **

CREATE TABLE task (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(64) NOT NULL,
	description TEXT NOT NULL,
	latitude TEXT(16) NOT NULL,
	longitude TEXT(16) NOT NULL,
	price FLOAT(8) NOT NULL,
	deadline DATETIME NOT NULL,
	created DATETIME NOT NULL DEFAULT NOW(),

	category_id INT,
	status_id INT,
	rating_id INT
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- **

CREATE TABLE task_image (
	id INT AUTO_INCREMENT PRIMARY KEY,
	image_path VARCHAR(45) NOT NULL,
	task_id INT NOT NULL
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- **

CREATE TABLE status (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title TEXT NOT NULL
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- **

CREATE TABLE rating (
	id INT AUTO_INCREMENT PRIMARY KEY,
	stars TINYINT(1) NOT NULL,
	rating FLOAT(3) DEFAULT 0
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- **

CREATE TABLE comment (
  id INT AUTO_INCREMENT PRIMARY KEY,

	-- NOTE: from table -> user
	user_id TEXT NOT NULL,
	ststus_id INT,
	rating_id INT,
	task_id INT
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- **

CREATE INDEX index_category ON category(id);

ALTER TABLE task ADD FOREIGN KEY (rating_id) REFERENCES rating(id);
ALTER TABLE comment ADD FOREIGN KEY (rating_id) REFERENCES rating(id);
ALTER TABLE comment ADD FOREIGN KEY (task_id) REFERENCES task(id);
ALTER TABLE comment ADD FOREIGN KEY (ststus_id) REFERENCES status(id);
ALTER TABLE task ADD FOREIGN KEY (status_id) REFERENCES status(id);
ALTER TABLE task_image ADD FOREIGN KEY (task_id) REFERENCES task(id);