<?php


namespace frontend\widgets;

use yii\bootstrap\Nav;
use yii\helpers\Html;


/**
 * Class MyNavWidget
 * @package frontend\widgets
 */
class MyNavWidget extends Nav
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        Html::removeCssClass($this->options, 'nav');
    }
}
