<?php


namespace frontend\components;

use yii\bootstrap\Nav;
use yii\helpers\Html;

class MyNavWidget extends Nav
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        Html::removeCssClass($this->options, 'nav');
    }
}
